#' Statistical Comparison of RSCU Values Between Groups
#'
#' Performs statistical analysis and generates boxplots and barplots for RSCU values
#' across user-defined groups. The function applies normality and variance tests to
#' select the appropriate statistical test (ANOVA, Welch ANOVA, or Kruskal-Wallis),
#' followed by post-hoc comparisons (Tukey HSD, pairwise t-test, or Dunn's test).
#' Results are visualized and saved as PNG files, and a summary table is exported as CSV.
#'
#' @param get_RSCU_out A data frame generated by \code{\link{get_RSCU}} containing RSCU values.
#' @param grouping_table A data frame with columns \code{Species} (matching sample names in \code{get_RSCU_out})
#'   and \code{group} (group assignment for each sample).
#' @param xlab Character string for the x-axis label.
#' @param width Width of the output plots in inches.
#' @param height Height of the output plots in inches.
#' @param res Resolution of the output plots in DPI (dots per inch).
#' @param p.adjust.method Method for p-value adjustment in post-hoc tests. One of
#'   \code{"holm"}, \code{"hochberg"}, \code{"hommel"}, \code{"bonferroni"}, \code{"BH"},
#'   \code{"BY"}, or \code{"fdr"}. Default is \code{"bonferroni"}.
#'
#' @return A data frame with post-hoc statistical results. Side effects: 
#'   - PNG files with boxplots and barplots are saved in the directories \code{selected_species} and \code{selected_species_barplots}.
#'   - A CSV file \code{Post_hoc_table_selected_species.csv} is saved in the working directory.
#'
#' @details
#' For each codon, the function:
#' \itemize{
#'   \item Tests for normality (Shapiro-Wilk) and homogeneity of variance (Levene's test)
#'   \item Selects the appropriate omnibus test (ANOVA, Welch ANOVA, or Kruskal-Wallis)
#'   \item Performs post-hoc comparisons with p-value adjustment
#'   \item Generates and saves boxplots and barplots with significance annotations
#' }
#' 
#' The function automatically creates the required output directories if they do not exist.
#'
#' @examples
#' data("prepared_fasta", package = "RSCUcaller")
#' rscu_data <- get_RSCU(prepared_fasta)
#' grouping_table <- data.frame(
#'   Species = unique(rscu_data$Species),
#'   group = rep(c("Group1", "Group2"), length.out = length(unique(rscu_data$Species)))
#' )
#' boxplot_between_groups(
#'   get_RSCU_out = rscu_data,
#'   grouping_table = grouping_table,
#'   width = 6,
#'   height = 6,
#'   xlab = "Group",
#'   res = 300,
#'   p.adjust.method = "bonferroni"
#' )
#'
#' @seealso
#' \code{\link{get_RSCU}}, \code{\link{stat_scat_box}}
#'
#' @export

boxplot_between_groups <-function(get_RSCU_out,grouping_table,width,height,xlab,res,p.adjust.method = "bonferroni") {
  
  if (base::missing(get_RSCU_out)) {
    stop("The get_RSCU_out predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }
  
  if (base::all(colnames(grouping_table)!=c("Species","group"))) {
    stop("Check the colnames of the grouping_table",
         call. = FALSE)
  }

  if (!(p.adjust.method %in% c("holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr"))) {
    stop('Invalid p.adjust.method  argument. Please choose from "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr" valid options.')
  }
  
  if (!base::file.exists("selected_species") & !base::file.exists("selected_species_barplots")){
    base::dir.create("selected_species")
    base::dir.create("selected_species_barplots")
  }
  
  if (base::file.exists("selected_species") & base::file.exists("selected_species_barplots")) {
    
    base::message(base::paste0("Calculating statistics and generating plots... "))

    make_tukey_test <- function (data,variable,grouping_variable){
  data %>% 
    rstatix::tukey_hsd(reformulate(grouping_variable, variable)) %>%
    rstatix::add_xy_position(x = grouping_variable)
}
    
    levene_warning_codons <- base::character()
    normality_warning_codons <- base::character()
    
    codons <- c("aaa", "aac", "aag", "aat", "aca", "acc", "acg", "act", "aga", "agc", "agg", "agt", "ata", "atc", "att", "caa", "cac", "cag", "cat", "cca", "ccc", "ccg", "cct",
                "cga", "cgc", "cgg", "cgt", "cta", "ctc", "ctg", "ctt", "gaa", "gac", "gag", "gat", "gca", "gcc", "gcg", "gct", "gga", "ggc", "ggg", "ggt", "gta", "gtc", "gtg", "gtt",
                "taa", "tac", "tag", "tat", "tca", "tcc", "tcg", "tct", "tga", "tgc", "tgt", "tta", "ttc", "ttg", "ttt")
    statistical_table <- base::data.frame(row.names = 1, group1 = NA, group2 = NA, p.adj=NA, p.adj.signif=NA,test=NA)
    get_RSCU_out <- merge(get_RSCU_out,grouping_table,by="Species")
    get_RSCU_out$index2 <- paste0(get_RSCU_out$group,"_",get_RSCU_out$codon)
    get_RSCU_out <- get_RSCU_out[order(get_RSCU_out$group),]
    
    for (i in 1:base::length(codons)) {
      table_1 <- get_RSCU_out[get_RSCU_out$codon %in% codons[i],]
      table_1 <- table_1[,c("RSCU", "index2","group")]
      
      test_used <- "Kruskal-Wallis"
      stat_p <- NA
      post_hoc <- NULL

      shapiro_test <- try(stats::shapiro.test(table_1$RSCU), silent = TRUE)
      
      if (!inherits(shapiro_test, "try-error") && shapiro_test$p.value >= 0.05) {
        
        levene_test <- rstatix::levene_test(RSCU ~ as.factor(index2), data = table_1)
        
        levene_p <- levene_test$p
        
        if (!is.na(levene_p) && levene_p >= 0.05) {
          
          aov_result <- stats::aov(RSCU ~ index2, data = table_1)
          
          stat_p <- base::summary(aov_result)[[1]]$`Pr(>F)`[1]
          
          test_used <- "ANOVA"
          
          post_hoc <- base::as.data.frame(make_tukey_test(data=table_1, variable = "RSCU ",grouping_variable = "index2"))
          
          post_hoc <- dplyr::arrange(.data = post_hoc, p.adj)
          
          post_hoc$test <- "ANOVA/TukeyHSD"
          
          post_hoc_x_y <- post_hoc
          
           } else {
          
             welch_result <- stats::oneway.test(RSCU ~ index2, data = table_1, var.equal = FALSE)
          
             stat_p <- welch_result$p.value
          
             test_used <- "Welch ANOVA"
        
             post_hoc <- as.data.frame(rstatix::pairwise_t_test(RSCU ~ index2, data = table_1, p.adjust.method = p.adjust.method))
             
             post_hoc <- dplyr::arrange(.data = post_hoc, p.adj)
             
             post_hoc_x_y <- rstatix::add_xy_position(post_hoc, x=post_hoc[2])
             
             post_hoc_x_y$test <- "Welch_ANOVA/Pairwise_t_test"

             levene_warning_codons <- c(levene_warning_codons, codons[i])
        }
      } else {
        
        normality_warning_codons <- c(normality_warning_codons, codons[i])
      }
      
      if (test_used == "Kruskal-Wallis") {
      
        stat <- stats::kruskal.test(RSCU ~ index2 , data = table_1)
      
        stat_p <- stat$p.value
      
        post_hoc <- base::as.data.frame(rstatix::dunn_test(RSCU ~ index2, data = table_1, p.adjust.method = p.adjust.method))
        
        post_hoc <- dplyr::arrange(.data = post_hoc, p.adj)
        
        post_hoc_x_y <- rstatix::add_xy_position(post_hoc, x=post_hoc[2])
        
        post_hoc_x_y$test <- "Kruskal-Wallis/Dunn"
      
        }

      post_hoc_stats <- post_hoc_x_y[,c("group1","group2","p.adj","p.adj.signif","test")]
      statistical_table <- base::rbind(statistical_table,post_hoc_stats)
      statistical_table <- statistical_table[!base::is.na(statistical_table$group1),]
      post_hoc_x_y <- post_hoc_x_y[,c("group1","group2","p.adj","p.adj.signif","y.position","groups","xmin","xmax","test")]
      plot_title <- paste0(codons[i], ", ", test_used, ", p=", format(stat_p, digits = 3))
      png(paste0("selected_species/",codons[i],".png"), width=width, height=height, units = "in", res=res)
      p <- ggpubr::ggboxplot(table_1,
                             x="group",
                             y="RSCU",
                             fill = "white",
                             color = "group",
                             xlab = xlab,
                             palette = c("dodgerblue3", "maroon2",  "forestgreen", "darkorange1", "blueviolet", "firebrick2",
                                         "deepskyblue", "orchid2", "chartreuse3", "gold", "slateblue1", "tomato" , "blue", "magenta", "green3",
                                         "yellow", "purple3", "red" ,"darkslategray1", "lightpink1", "lightgreen", "khaki1", "plum3", "salmon")) +
        ggpubr::stat_pvalue_manual(post_hoc_x_y, label="p.adj.signif", hide.ns=TRUE) +
        ggplot2::geom_jitter(aes(color = group), width = 0.2, height = 0) +
        ggplot2::theme(legend.position = "none") +
        ggplot2::scale_x_discrete() +
        ggplot2::ggtitle(base::paste0(plot_title))
      base::print(p)
      dev.off()
      table_1 <- table_1 %>% dplyr::group_by(group) %>% dplyr::summarize(`RSCU` = mean(RSCU))
      get_RSCU_out_groups <- get_RSCU_out[!duplicated(get_RSCU_out$group),]
      idx <- base::match(table_1$group,get_RSCU_out_groups$group)
      table_1 <- table_1[idx,]
      png(paste0("selected_species_barplots/", codons[i], ".png"), width = width, height = height, units = "in", res = res)
      p <- ggpubr::ggbarplot(table_1, 
                             x = "group", 
                             y = "RSCU", 
                             fill = "group", 
                             color = "group",
                             xlab = xlab,
                             palette = c("dodgerblue3", "maroon2",  "forestgreen", "darkorange1", "blueviolet", "firebrick2",
                                         "deepskyblue", "orchid2", "chartreuse3", "gold", "slateblue1", "tomato" , "blue", "magenta", "green3",
                                         "yellow", "purple3", "red" ,"darkslategray1", "lightpink1", "lightgreen", "khaki1", "plum3", "salmon")) + 
        ggpubr::stat_pvalue_manual(post_hoc_x_y,label = "p.adj.signif", hide.ns = TRUE) + 
        ggplot2::theme(legend.position = "none") + 
        ggplot2::scale_x_discrete() + 
        ggplot2::ggtitle(base::paste0(plot_title)) + 
                           ggplot2::ylab("mean(RSCU)")
      base::print(p)
      dev.off()
    }
    if (length(levene_warning_codons) > 0) {
      message("\n Significant variance heterogeneity detected in:\n",
              paste(levene_warning_codons, collapse = ", "), 
              "\nUsed Welch ANOVA for these cases.")
    }
    
    if (length(normality_warning_codons) > 0) {
      message("\n Non-normal distributions detected in:\n",
              paste(normality_warning_codons, collapse = ", "), 
              "\nUsed Kruskal-Wallis test for these cases.")
    }
  }
  else (
    stop("Try to make directory selected_species & selected_species_barplots manually and run function again",
         call. = FALSE)
  )
  
  
  base::message(base::paste0("Done! Check selected_species & selected_species_barplots dir !!!"))
  write.csv2(statistical_table,"Post_hoc_table_selected_species.csv",row.names = FALSE)
  return(statistical_table)
}