#' Correlation Analysis of RSCU Values Between Two Species
#'
#' Performs Pearson correlation analysis and generates a scatter plot to compare
#' Relative Synonymous Codon Usage (RSCU) values between two biological samples.
#'
#' @param get_RSCU_out A data frame generated by \code{\link{get_RSCU}} containing RSCU values
#' @param Species_x Character string specifying the column name in \code{get_RSCU_out}
#'                 for the x-axis sample (must match \code{Species} column values)
#' @param Species_y Character string specifying the column name in \code{get_RSCU_out}
#'                 for the y-axis sample (must match \code{Species} column values)
#' @param xlab Label for x-axis (typically sample name/organism)
#' @param ylab Label for y-axis (typically sample name/organism)
#'
#' @return A list containing:
#' \itemize{
#'   \item \code{res} - Pearson correlation results object from \code{cor.test}
#'   \item \code{plot} - ggplot2 object displaying the scatter plot with regression line
#' }
#'
#' @details
#' This function enables comparative analysis of codon usage patterns between two samples.
#' The plot includes:
#' \itemize{
#'   \item Jittered points to avoid overplotting
#'   \item Linear regression line with 95% confidence interval
#'   \item Annotation with correlation coefficient (R), p-value, and confidence interval
#' }
#'
#' @examples
#' data("prepared_fasta", package = "RSCUcaller")
#' rscu_data <- get_RSCU(prepared_fasta)
#' 
#' # Compare two samples
#'
#' cor_result <- correlation(
#'   get_RSCU_out = rscu_data,
#'   Species_x = "Apopellia_endiviifolia_B1",
#'   Species_y = "Apopellia_endiviifolia_A1",
#'   xlab = "B1",
#'   ylab = "A1"
#' )
#' 
#' # Access results
#' print(cor_result$res)
#' print(cor_result$plot)
#'
#' @references
#' Pearson, K. (1895). "Notes on regression and inheritance in the case of two parents". 
#' Proceedings of the Royal Society of London. 58: 240–242.
#'
#' @seealso
#' Related functions:
#' \code{\link{get_RSCU}} for generating input data,
#' \code{\link{heatmap_RSCU}} for multivariate visualization
#'
#' @importFrom ggplot2 aes geom_point geom_smooth theme_bw xlab ylab ggtitle
#' @importFrom stats cor.test lm
#' @export

correlation <- function(get_RSCU_out,Species_x,Species_y,xlab,ylab) {

  if (base::missing(get_RSCU_out)) {
    stop("The get_RSCU_out predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  if (base::missing(Species_x)) {
    stop("The Species_x predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  if (base::missing(Species_y)) {
    stop("The Species_y predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  get_RSCU_out_x <- get_RSCU_out[get_RSCU_out$Species %in% Species_x,]
  get_RSCU_out_y <- get_RSCU_out[get_RSCU_out$Species %in% Species_y,]
  correlation_xy <- base::merge(get_RSCU_out_x,get_RSCU_out_y,by="codon")
  res <- stats::cor.test(correlation_xy$RSCU.x, correlation_xy$RSCU.y, method = 'pearson')

  p <- ggplot2::ggplot(data = correlation_xy,mapping=aes(x = RSCU.x,
                                                         y = RSCU.y,
                                                         add="jitter"))+
    ggplot2::geom_point(shape=21,
                        fill='steelblue3',
                        color='white',
                        size = 3,
                        alpha=0.5)+
    ggplot2::geom_smooth(method=lm,
                         color='red4')+
    smplot2::sm_statCorr(show_text = FALSE,
                         col="red4")+
    ggplot2::theme_bw()+
    ggplot2::xlab(xlab)+
    ggplot2::ylab(ylab)+
    ggplot2::ggtitle(base::paste0("R=",base::round(res$estimate,2),", ","p-value=",base::round(res$p.value,3),", ","95% conf.int=",round(res$conf.int,2)))

  return(list(res=res,plot=p))

}
