#' Convert RSCU Results to Analysis-Ready Matrix
#' 
#' Transforms RSCU (Relative Synonymous Codon Usage) results from long to wide format,
#' creating a matrix suitable for multivariate analysis and visualization.
#'
#' @param get_RSCU_out A data frame generated by \code{\link{get_RSCU}}, 
#'   \code{\link{get_RSCU_other}} or \code{\link{get_RSCU_other2}} containing
#'   RSCU values for multiple samples.
#'
#' @return A list containing two elements:
#' \describe{
#'   \item{matrix}{Numeric matrix with samples as rows (rownames = sample IDs) 
#'     and codon-AA pairs as columns (format: "AA | codon")}
#'   \item{df_matrix}{Data frame version of the matrix with an additional 
#'     "Sample" column}
#' }
#' 
#' @details
#' This function restructures RSCU data into a format compatible with:
#' \itemize{
#'   \item Multivariate statistics (PCA, clustering)
#'   \item Machine learning algorithms
#'   \item Heatmap visualizations
#' }
#' The matrix format preserves the relationship between amino acids and their 
#' synonymous codons while enabling sample-wise comparisons.
#'
#' @examples
#' # Using built-in data
#' data("prepared_fasta", package = "RSCUcaller")
#' rscu_data <- get_RSCU(prepared_fasta)
#' matrix_result <- get_matrix(rscu_data)
#' 
#' 
#' @seealso
#' Related functions:
#' \code{\link{get_RSCU}} for generating input data,
#' \code{\link{PCA_RSCU}} for dimensionality reduction,
#' \code{\link{heatmap_RSCU}} for visualization
#' 
#' @importFrom magrittr %>%
#' @importFrom dplyr filter group_by mutate
#' @importFrom stats setNames
#' @export

get_matrix <- function(get_RSCU_out=get_RSCU_out){

  if (base::missing(get_RSCU_out)) {
    stop("The get_RSCU_out predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  base::message(base::paste0("Generating matrix... "))

  RSCU_table <- get_RSCU_out[,c("Species","RSCU","AA","codon")]
  RSCU_table$AAcodon <- base::paste0(RSCU_table$AA," | ",RSCU_table$codon)
  RSCU_table$codon <- NULL
  RSCU_table$AA <- NULL
  matrix_RSCU <- base::matrix(ncol=64,nrow=length(unique(RSCU_table$Species)))
  base::colnames(matrix_RSCU) <- base::unique(RSCU_table$AAcodon)
  base::rownames(matrix_RSCU) <- base::unique(RSCU_table$Species)
  matrix_RSCU <- as.data.frame(matrix_RSCU)

  for (i in 1:base::nrow(matrix_RSCU)) {
    j <- 64*i-63
    j <- base::as.numeric(j)
    k <- 64 * i
    k <- base::as.numeric(k)
    lista_rscu <- RSCU_table$RSCU[j:k]
    matrix_RSCU[i,] <- base::ifelse(
      base::rownames(matrix_RSCU)[i] %in% RSCU_table$Species & base::colnames(matrix_RSCU) %in% RSCU_table$AAcodon,
      lista_rscu, matrix_RSCU[i,])
  }
  base::message(base::paste0("Success"))
  return(matrix_RSCU)
}
