#' Comparative Visualization of RSCU Distributions Between Two Datasets
#' 
#' Generates a dual-panel histogram comparing Relative Synonymous Codon Usage (RSCU) 
#' patterns between two experimental conditions or biological groups.
#'
#' @param get_RSCU_out_left A data frame generated by \code{\link{get_RSCU}} containing
#'   RSCU values for the left-side panel
#' @param get_RSCU_out_right A data frame generated by \code{\link{get_RSCU}} containing
#'   RSCU values for the right-side panel
#' @param title_left Title for left panel (typically control/condition 1)
#' @param title_right Title for right panel (typically treatment/condition 2)
#'
#' @return A \code{patchwork} object combining:
#' \itemize{
#'   \item Left panel: Reversed RSCU histogram
#'   \item Central panel: Codon and amino acid labels
#'   \item Right panel: Standard RSCU histogram
#'   \item Legend: Sample grouping information
#' }
#' 
#' @details
#' This visualization enables direct comparison of codon usage patterns between two datasets.
#' Key features:
#' \itemize{
#'   \item Mirror-image histogram layout for easy comparison
#'   \item Integrated codon and amino acid annotations
#'   \item Automated color consistency between panels
#'   \item Flexible group labeling through \code{get_RSCU} input structure
#' }
#' The function requires synchronized factor levels in both input datasets for proper alignment.
#'
#' @examples
#' data("prepared_fasta", package = "RSCUcaller")
#' rscu_control <- get_RSCU(prepared_fasta)
#' rscu_treatment <- get_RSCU(prepared_fasta)
#' 
#' histogram_RSCU_double(
#'   get_RSCU_out_left = rscu_control,
#'   get_RSCU_out_right = rscu_treatment,
#'   title_left = "Control Group",
#'   title_right = "Treatment Group"
#' )
#'
#' @seealso
#' Related visualization functions:
#' \code{\link{histogram_RSCU}}, \code{\link{heatmap_RSCU}}
#' 
#' @export
#' @importFrom forcats fct_rev

histogram_RSCU_double <- function(get_RSCU_out_left=get_RSCU_out,get_RSCU_out_right=get_RSCU_out,title_left="",title_right=""){

  if (base::missing(get_RSCU_out_left)) {
    stop("The get_RSCU_out_left predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  if (base::missing(get_RSCU_out_right)) {
    stop("The get_RSCU_out_right predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  base::message(base::paste0("Generating plot... "))

  get_RSCU_out_right$Col2 <- 1
  get_RSCU_out_right$Col2 <- as.factor(get_RSCU_out_right$Col2)

  p0<-ggplot2::ggplot(data=get_RSCU_out_right, aes(x=index, y=RSCU, fill=Col))+
    ggplot2::geom_bar(stat='identity')+
    ggplot2::theme_minimal()+
    ggplot2::coord_flip()+
    ggplot2::ggtitle(title_right)+
    ggplot2::theme(axis.text.y=element_blank(),
                   axis.ticks.y=element_blank(),
                   axis.ticks.x=element_blank(),
                   axis.title.y=element_blank(),
                   legend.position="none",
                   panel.grid.major = element_blank(),
                   panel.border = element_blank(),
                   panel.background = element_blank(),
                   plot.title = element_text(hjust = 0.5))


  p1<-ggplot2::ggplot(data=get_RSCU_out_right)+
    ggplot2::geom_tile(aes(x=AA, y=fct_rev(Col),fill=Col),col="white")+
    ggplot2::geom_text(aes(x=AA, y=Col,label=codon),col="white")+
    ggplot2::theme_void()+
    ggplot2::theme(legend.position="none")+
    ggplot2::coord_flip()

  p3<-ggplot2::ggplot(data=get_RSCU_out_left, aes(x=index, y=RSCU, fill=Col))+
    ggplot2::geom_bar(stat='identity')+
    ggplot2::theme_minimal()+
    ggplot2::ylab("RSCU")+
    ggplot2::scale_y_reverse()+
    ggplot2::coord_flip()+
    ggplot2::ggtitle(title_left)+
    ggplot2::theme(axis.text.y=element_blank(),
                   axis.ticks.y=element_blank(),
                   axis.ticks.x=element_blank(),
                   axis.title.y=element_blank(),
                   panel.grid.major = element_blank(),
                   panel.border = element_blank(),
                   panel.background = ggplot2::element_blank(),
                   plot.title = ggplot2::element_text(hjust = 0.5),
                   legend.position="none")

  p4<-ggplot2::ggplot(data=get_RSCU_out_right)+
    ggplot2::geom_tile(aes(x=AA, y=forcats::fct_rev(Col2)),col="white")+
    ggplot2::geom_text(aes(x=AA, y=Col2,label=AA),col="white", fontface = "bold",angle = 90)+
    ggplot2::theme_void()+
    ggplot2::theme(legend.position="none")+
    ggplot2::coord_flip()+
    ggplot2::ggtitle("")

  p5<-ggplot2::ggplot(data=get_RSCU_out_right)+
    ggplot2::geom_tile(aes(x=index, y=forcats::fct_rev(Col[1]),fill=Species),col="white")+
    ggplot2::theme_void()+theme(legend.position="right")+
    ggplot2::coord_flip()+
    ggplot2::ggtitle("")

  p<-p3+p4+p1+p0+p5+patchwork::plot_layout(ncol = 5, widths = c(2,0.2,1,2,0.5))

  base::message(base::paste0("Success"))
  return(p)
}

histogram_RSCU_double <- function(get_RSCU_out_left=get_RSCU_out,get_RSCU_out_right=get_RSCU_out,title_left="",title_right=""){

  if (base::missing(get_RSCU_out_left)) {
    stop("The get_RSCU_out_left predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  if (base::missing(get_RSCU_out_right)) {
    stop("The get_RSCU_out_right predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  base::message(base::paste0("Generating plot... "))

  get_RSCU_out_right$Col2 <- 1
  get_RSCU_out_right$Col2 <- as.factor(get_RSCU_out_right$Col2)

  p0<-ggplot2::ggplot(data=get_RSCU_out_right, aes(x=index, y=RSCU, fill=Col))+
    ggplot2::geom_bar(stat='identity')+
    ggplot2::theme_minimal()+
    ggplot2::coord_flip()+
    ggplot2::ggtitle(title_right)+
    ggplot2::theme(axis.text.y=element_blank(),
                   axis.ticks.y=element_blank(),
                   axis.ticks.x=element_blank(),
                   axis.title.y=element_blank(),
                   legend.position="none",
                   panel.grid.major = element_blank(),
                   panel.border = element_blank(),
                   panel.background = element_blank(),
                   plot.title = element_text(hjust = 0.5))


  p1<-ggplot2::ggplot(data=get_RSCU_out_right)+
    ggplot2::geom_tile(aes(x=AA, y=fct_rev(Col),fill=Col),col="white")+
    ggplot2::geom_text(aes(x=AA, y=Col,label=codon),col="white")+
    ggplot2::theme_void()+
    ggplot2::theme(legend.position="none")+
    ggplot2::coord_flip()

  p3<-ggplot2::ggplot(data=get_RSCU_out_left, aes(x=index, y=RSCU, fill=Col))+
    ggplot2::geom_bar(stat='identity')+
    ggplot2::theme_minimal()+
    ggplot2::ylab("RSCU")+
    ggplot2::scale_y_reverse()+
    ggplot2::coord_flip()+
    ggplot2::ggtitle(title_left)+
    ggplot2::theme(axis.text.y=element_blank(),
                   axis.ticks.y=element_blank(),
                   axis.ticks.x=element_blank(),
                   axis.title.y=element_blank(),
                   panel.grid.major = element_blank(),
                   panel.border = element_blank(),
                   panel.background = ggplot2::element_blank(),
                   plot.title = ggplot2::element_text(hjust = 0.5),
                   legend.position="none")

  p4<-ggplot2::ggplot(data=get_RSCU_out_right)+
    ggplot2::geom_tile(aes(x=AA, y=forcats::fct_rev(Col2)),col="white")+
    ggplot2::geom_text(aes(x=AA, y=Col2,label=AA),col="white", fontface = "bold",angle = 90)+
    ggplot2::theme_void()+
    ggplot2::theme(legend.position="none")+
    ggplot2::coord_flip()+
    ggplot2::ggtitle("")

  p5<-ggplot2::ggplot(data=get_RSCU_out_right)+
    ggplot2::geom_tile(aes(x=index, y=forcats::fct_rev(Col[1]),fill=Species),col="white")+
    ggplot2::theme_void()+theme(legend.position="right")+
    ggplot2::coord_flip()+
    ggplot2::ggtitle("")

  p<-p3+p4+p1+p0+p5+patchwork::plot_layout(ncol = 5, widths = c(2,0.2,1,2,0.5))

  base::message(base::paste0("Success"))
  return(p)
}
