#' Principal Component Analysis of RSCU Patterns
#' 
#' Performs dimensionality reduction on Relative Synonymous Codon Usage (RSCU) data
#' using Principal Component Analysis (PCA) and visualizes sample clustering.
#'
#' @param get_matrix_out A list object generated by \code{\link{get_matrix}} containing
#'   RSCU values in matrix format
#' @param grouping_table A data frame with columns:
#'   \itemize{
#'     \item \code{Species} - matching row names in \code{get_matrix_out$matrix}
#'     \item \code{group} - categorical variable for sample coloring
#'   }
#'
#' @return A \code{ggplot2} object showing PCA results with:
#' \itemize{
#'   \item Points colored by experimental group
#'   \item Axis labels showing explained variance percentages
#'   \item Minimal theme optimized for readability
#' }
#' 
#' @details
#' This visualization helps identify global patterns in codon usage bias across samples.
#' Key features:
#' \itemize{
#'   \item Uses covariance matrix for PCA (no scaling)
#'   \item Labels show percentage of variance explained by each principal component
#'   \ Automatically handles sample-group mapping through \code{grouping_table}
#' }
#'
#' @examples
#' data("prepared_fasta", package = "RSCUcaller")
#' rscu_data <- get_RSCU(prepared_fasta)
#' matrix_data <- get_matrix(rscu_data)
#' 
#' # Create grouping table
#' groups <- data.frame(
#'   Species = rownames(matrix_data$matrix),
#'   group = rep(c("Group1", "Group2"), length.out = nrow(matrix_data$matrix))
#' )
#' 
#' # Generate PCA plot
#' pca_plot <- PCA_RSCU(matrix_data, groups)
#' print(pca_plot)
#'
#' @references
#' Jolliffe, I.T. (2002). Principal Component Analysis (2nd ed.). Springer.
#' 
#' @seealso
#' Related functions:
#' \code{\link{get_matrix}} for input data preparation,
#' \code{\link{heatmap_RSCU}} for alternative visualization
#'
#' @export

PCA_RSCU <- function(get_matrix_out=get_matrix_out,grouping_table=grouping_table){
  
  if (base::missing(get_matrix_out)) {
    stop("The get_matrix_out predictions are required. Please provide a valid argument.",
         call. = FALSE)
  }

  pca <- stats::prcomp(get_matrix_out, scale. = FALSE)
  pca_data <- base::as.data.frame(pca$x)
  pca_data$names <- base::rownames(get_matrix_out)
  pca_data <- base::merge(pca_data,grouping_table,by.x="names",by.y="Species",all.x = TRUE)
  
  PCA_plot <- ggplot2::ggplot(pca_data, aes(x = PC1, y = PC2, label = names,color = group)) +
    ggplot2::geom_point(size = 3) +
    ggplot2::xlab(base::paste0("PC1 (", base::round(base::summary(pca)$importance[2,1]*100, 1), "%)")) +
    ggplot2::ylab(base::paste0("PC2 (", base::round(base::summary(pca)$importance[2,2]*100, 1), "%)")) +
    ggplot2::ggtitle("PCA") +
    ggplot2::theme_bw()+
    ggplot2::theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
  
  return(PCA_plot)
  
  base::message(base::paste0("Success"))
  
}